const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/d1.jpg',
            price: 120, countInStock: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 10,
            description: 'high quality products',
        },
        {
            _id:'2',
            name:'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/d1.jpg',
            price: 120, countInStock: 20,
            brand: 'Nike',
            rating: 2,
            numReviews: 10,
            description: 'high quality products',
        },
        {
            _id:'3',
            name:'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/d1.jpg',
            price: 120, countInStock: 30,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality products',
        },
        {
            _id:'4',
            name:'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/d1.jpg',
            price: 120, countInStock: 25,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'high quality products',
        },
        {
            _id:'5',
            name:'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/d1.jpg',
            price: 120, countInStock:0,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'high quality products',
        },
    ],
};
export default data;
